### PR TITLE
bencode.metainfo.reader/torrent-name: get 'name.utf-8' field first

### PR DESCRIPTION
**Pull request by number23**
fix torrent-name return better, :-)

### CODE REVIEW

**Comment by danielfm** [comment]
Thanks for your pull request!

Could you please write a test case for that as well?

**Comment by number23** [comment]
OK, added a test case.

**Comment by number23** [comment]
lein test bencode.metainfo.reader-test

Ran 7 tests containing 30 assertions.
0 failures, 0 errors.

**Comment by danielfm** [comment]
Thanks!

**Pull request merged**
